name: Quality

on:
  workflow_dispatch:

  push:
    branches:
      - develop
      - main

  pull_request:
    branches:
      - develop
      - main

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Ruff
        run: |
          pip install ruff

      - name: Run Ruff
        run